# Generated by Django 2.0.6 on 2018-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinstance',
            name='picture',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='animalinstance',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('f', 'Flat'), ('c', 'Curly'), ('w', 'Wiry'), ('l', 'Fluffy'), ('s', 'Smooth')], help_text='Please select the type of hair it has.', max_length=1),
        ),
    ]
