# Generated by Django 2.0.6 on 2018-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180911_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinstance',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
